
let jokes = [
    "Why don’t skeletons fight each other? They don’t have the guts!",
    "What do you call fake spaghetti? An impasta.",
    "Why don’t scientists trust atoms? Because they make up everything.",
    "Why did the scarecrow win an award? He was outstanding in his field.",
    "Why can’t your nose be 12 inches long? Because then it would be a foot.",
    "Why do cows wear bells? Because their horns don’t work.",
    "What’s orange and sounds like a parrot? A carrot.",
    "How does a penguin build its house? Igloos it together.",
    "Why couldn’t the bicycle stand up by itself? It was two-tired.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "What did the fish say when it hit the wall? Dam.",
    "How do you organize a space party? You planet.",
    "What’s Forrest Gump’s password? 1Forrest1.",
    "Why did the computer go to the doctor? It caught a virus.",
    "What do you call a bear with no teeth? A gummy bear.",
    "Why did the math book look sad? It had too many problems.",
    "What do you call cheese that isn’t yours? Nacho cheese.",
    "Why don’t eggs tell jokes? They’d crack each other up.",
    "How do you make a tissue dance? Put a little boogie in it.",
    "Why couldn’t the leopard play hide and seek? Because he was always spotted.",
    "What do you call a pile of cats? A meowtain.",
    "Why are ghosts bad liars? Because you can see right through them.",
    "Why did the tomato turn red? It saw the salad dressing.",
    "What do you call a can opener that doesn’t work? A can’t opener.",
    "Why don’t seagulls fly over the bay? Because then they’d be bagels.",
    "What’s brown and sticky? A stick.",
    "Why did the bicycle fall over? Because it was two-tired.",
    "How do you make holy water? You boil the hell out of it.",
    "What do you call an alligator in a vest? An investigator.",
    "Why did the photo go to jail? It was framed.",
    "What did the zero say to the eight? Nice belt!",
    "What’s the difference between a hippo and a zippo? One is heavy, and the other is a little lighter.",
    "Why don’t oysters donate to charity? Because they’re shellfish.",
    "Why can’t your nose be 12 inches long? Because then it’d be a foot.",
    "What do you get when you cross a snowman and a dog? Frostbite.",
    "Why did the chicken go to the séance? To talk to the other side.",
    "What do you call a boomerang that doesn’t come back? A stick.",
    "Why did the stadium get hot after the game? All the fans left.",
    "Why don’t melons get married? Because they cantaloupe.",
    "What did one wall say to the other wall? I’ll meet you at the corner.",
    "What do you call a factory that makes OK products? A satisfactory.",
    "What’s the best way to watch a fly fishing tournament? Live stream.",
    "Why was the math teacher suspicious? Too many shady figures.",
    "Why did the coffee file a police report? It got mugged.",
    "How do you catch a squirrel? Climb a tree and act like a nut.",
    "What do you call two birds in love? Tweethearts.",
    "What kind of shoes do ninjas wear? Sneakers.",
    "Why do bees have sticky hair? Because they use honeycombs.",
    "Why don’t skeletons ever go trick or treating? They don’t have the guts.",
    "What do you call a fake noodle? An impasta.",
    "What did one hat say to the other? Stay here! I’m going on ahead.",
    "Why couldn’t the pirate finish the alphabet? Because he got lost at C.",
    "What did the grape do when it got stepped on? Nothing but let out a little wine.",
    "Why did the computer break up with the internet? There was no connection.",
    "What do you call a dog magician? A labracadabrador.",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus.",
    "Why can’t you give Elsa a balloon? Because she’ll let it go.",
    "How does a train eat? It goes chew chew.",
    "Why was the broom late? It swept in.",
    "Why are elevator jokes so classic? They work on so many levels.",
    "What do you call a fish with no eyes? Fsh.",
    "Why was the music teacher sad? Her students were out of tune.",
    "What kind of car does a Jedi drive? A Toy-Yoda.",
    "Why are frogs so happy? They eat whatever bugs them.",
    "Why did the belt go to jail? It held up a pair of pants.",
    "What do you call a fish that wears a crown? A kingfish.",
    "How do you keep a bull from charging? Take away its credit card.",
    "What’s a vampire’s favorite fruit? A blood orange.",
    "Why don’t trees use computers? They’re afraid of logging in.",
    "What do you call a funny mountain? Hill-arious.",
    "Why don’t we ever tell secrets on a farm? Because the potatoes have eyes and the corn has ears.",
    "Why don’t pirates take baths before walking the plank? Because they just wash up on shore.",
    "What’s a cat’s favorite color? Purr-ple.",
    "Why did the cow jump over the moon? The farmer had cold hands.",
    "What do you call a sleeping bull? A bulldozer.",
    "Why did the clock get kicked out of class? It was tocking too much.",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "Why do bananas never get lonely? Because they hang out in bunches.",
    "How do you throw a space party? You planet.",
    "Why did the man put his money in the blender? He wanted liquid assets.",
    "Why did the shoe go to school? To get a little sole education.",
    "Why don’t bakers ever stop working? They knead the dough.",
    "What do you call a sleeping dinosaur? A dino-snore.",
    "Why did the teddy bear say no to dessert? Because it was stuffed.",
    "What do you get when you cross a vampire and a snowman? Frostbite.",
    "Why did the bicycle collapse? It was two-tired.",
    "What’s a skeleton’s least favorite room? The living room.",
    "Why did the cookie cry? Because its mother was a wafer so long.",
    "What do you call a bear in the rain? A drizzly bear.",
    "Why did the astronaut break up with his girlfriend? She needed space.",
    "How do you organize a party in space? You planet.",
    "Why don’t ants get sick? Because they have tiny ant-bodies.",
    "What did the grape say when it got squished? Nothing, it just let out a little wine.",
    "Why did the frog take the bus? His car got toad away."
];
window.onload = showRandomJoke();
function showRandomJoke(){
let  randomnumber=Math.floor((Math.random())*100);
document.getElementById("pp").innerHTML=""+jokes[randomnumber]+"";
}